### ISSUE TITLE
failUnsetUniforms setting is ignored

### ISSUE THREAD

**Issue by bchirlsbiodigital** [greggman/webgl-lint#20]
Hi, me again. Thanks again for yet another great tool...

I don't see where in the code `failUnsetUniforms` is ever actually checked, and it has no effect in my code. Maybe it was accidentally deleted along the way somewhere?

**Comment by greggman** [comment]
doh!  😅

https://github.com/greggman/webgl-lint/commit/e2d7e0373c009760176b65f3739e453e25dcbca8

**Comment by bchirlsbiodigital** [comment]
You are unbelievably fast. Thank you again.

**Comment by bchirlsbiodigital** [comment]
I haven't been this offended since Crockford.

**Comment by greggman** [comment]
Sorry, I didn't get the reference 😅

**Comment by bchirlsbiodigital** [comment]
webgl-lint calls me out for all the mistakes in my code. reminds me of the first time I ran jslint with all the settings turned up. ;-)
