### ISSUE TITLE
checkAttributesForBufferOverflow fails incorrectly in drawElements

### ISSUE THREAD

**Issue by brianchirls** [greggman/webgl-lint#21]
It looks like the highest vertex index is calculated incorrectly, if the indices array is part of a larger `ArrayBuffer`. I think it's scanning the entire ArrayBuffer, rather than just the subset of it that was originally referenced by the indices typed array.

Here is a test case:
https://codesandbox.io/s/webgl-lint-buffer-test-2b4rr?file=/src/index.js

You can replace line 37 with line 42 to see the error go away. I recommend debug stepping into `twgl.drawBufferInfo` until you get to `getLastUsedIndexForDrawElements`.

B

**Comment by greggman** [comment]
Thanks! I hope it doesn't turn out all the message you find are actually my bugs   😂

https://github.com/greggman/webgl-lint/commit/34f64a18c8ccdd162e12b5f1f48e3073259e5d0d

**Comment by brianchirls** [comment]
That did it! Thanks again for the quick fix.

If it makes you feel any better, I have a whole bunch of unset uniforms.
