### ISSUE TITLE
Incorrect validation for bufferSubData

### ISSUE THREAD

**Issue by bhouston** [greggman/webgl-lint#26]
I got this error:
```
webgl-lint.js:2197 Uncaught (in promise) Error: https://greggman.github.io/webgl-lint/webgl-lint.js:3042: error in bufferSubData(ARRAY_BUFFER{WebGLBuffer("*UNTAGGED:Buffer1*")}, 0, [object ArrayBuffer]): argument 2 is not a array or typedarray
    at reportError (webgl-lint.js:2197:15)
    at reportFunctionError (webgl-lint.js:3000:7)
    at checkArgs (webgl-lint.js:3042:19)
    at ctx.<computed> [as bufferSubData] (webgl-lint.js:3092:9)
```

But if you read the docs, it is completely allowed to pass in an ArrayBuffer into argument 2:
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bufferSubData

Specifically it can be "An [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer), [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer), a [DataView](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView), or a [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) that will be copied into the data store."

I did explicitly check the type of the data I am passing it, and it is:
```
arrayBuffer 
ArrayBuffer(737280)
byteLength: 737280
```

**Comment by greggman** [comment]
I'll fix it

Just fyi though: MDN is not the docs. The docs are here: [[WebGL]], (https://registry.khronos.org/webgl/specs/latest/1.0/) [[WebGL2]](https://registry.khronos.org/webgl/specs/latest/2.0/   MDN is often wrong and/or out of date

Also, WebGL didn't ship allowing ArrayBuffer. That was added later

**Comment by greggman** [comment]
it should be fixed: https://github.com/greggman/webgl-lint/commit/11e2a138e77f2a833a9b3f9427f16b91f70036b7
